import React from "react";
import { PageHero } from "../components/PageHero";

export const PrivacyPolicy: React.FC = () => {
  return (
    <main className="bg-gray-50 min-h-screen">
      <PageHero 
        title="Privacy Policy" 
        breadcrumb="Privacy Policy" 
      />

      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 bg-white p-8 md:p-12 shadow-sm rounded-xl">
          <div className="prose prose-blue max-w-none text-gray-700">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure
              of Your information when You use the Service and tells You about Your privacy rights and how
              the law protects You.
            </p>
            <p>
              We use Your Personal Data to provide and improve the Service. By using the Service, You
              agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Interpretation and Definitions</h2>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-3">Interpretation</h3>
            <p>
              The words whose initial letters are capitalized have meanings defined under the following
              conditions. The following definitions shall have the same meaning regardless of whether they
              appear in singular or in plural.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-3">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-2 my-4">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us", or "Our" in this Agreement) refers to Dr. Aravind Manoharan – Gastroenterology & GI Surgery Specialist.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Tamil Nadu, India.</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone, or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, provide the Service on behalf of the Company, perform services related to the Service, or assist the Company in analyzing how the Service is used.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>Website</strong> refers to Dr. Aravind Manoharan – Gastroenterology & GI Surgery Specialist Website.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Collecting and Using Your Personal Data</h2>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-3">Types of Data Collected</h3>
            
            <h4 className="text-lg font-bold text-gray-800 mt-4 mb-2">Personal Data</h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain personally identifiable
              information that can be used to contact or identify You. Personally identifiable information may
              include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2 my-4">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-bold text-gray-800 mt-4 mb-2">Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>
              Usage Data may include information such as Your Device's Internet Protocol address (e.g., IP
              address), browser type, browser version, pages of our Service that You visit, time and date of
              Your visit, time spent on those pages, unique device identifiers, and other diagnostic data.
            </p>
            <p>
              When You access the Service by or through a mobile device, We may collect certain information
              automatically, including but not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2 my-4">
              <li>Type of mobile device You use</li>
              <li>Mobile device unique ID</li>
              <li>IP address of Your mobile device</li>
              <li>Mobile operating system</li>
              <li>Type of mobile Internet browser You use</li>
              <li>Unique device identifiers and diagnostic data</li>
            </ul>
            <p>We may also collect information that Your browser sends whenever You visit Our Service.</p>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-3">Tracking Technologies and Cookies</h3>
            <p>
              We use Cookies and similar tracking technologies to track activity on Our Service and store
              certain information.
            </p>
            <p>Tracking technologies used may include:</p>
            <ul className="list-disc pl-6 space-y-2 my-4">
              <li>Cookies or Browser Cookies</li>
              <li>Web Beacons</li>
              <li>Tags and Scripts</li>
            </ul>
            <p>Cookies can be "Persistent" or "Session" Cookies.</p>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-3">Types of Cookies We Use</h3>

            <div className="space-y-4 my-4">
              <div>
                <strong>Necessary / Essential Cookies</strong><br />
                Type: Session Cookies<br />
                Administered by: Us<br />
                These Cookies are essential to provide You with services available through the Website and enable You to use some of its features.
              </div>
              
              <div>
                <strong>Cookies Policy / Notice Acceptance Cookies</strong><br />
                Type: Persistent Cookies<br />
                Administered by: Us<br />
                These Cookies identify whether users have accepted the use of cookies on the Website.
              </div>

              <div>
                <strong>Functionality Cookies</strong><br />
                Type: Persistent Cookies<br />
                Administered by: Us<br />
                These Cookies allow us to remember choices You make when You use the Website.
              </div>
            </div>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2 my-4">
              <li>To provide and maintain our Service</li>
              <li>To manage Your Account</li>
              <li>To contact You by email, phone calls, SMS, or other communication methods</li>
              <li>To provide updates, offers, and healthcare-related information</li>
              <li>To manage Your requests and appointments</li>
              <li>To improve our services, website functionality, and user experience</li>
              <li>For legal compliance and security purposes</li>
            </ul>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Sharing of Your Personal Information</h2>
            <p>We may share Your personal information in the following situations:</p>
            <ul className="list-disc pl-6 space-y-2 my-4">
              <li>With Service Providers</li>
              <li>With Affiliates</li>
              <li>With business partners</li>
              <li>During business transfers such as mergers or acquisitions</li>
              <li>When required by law</li>
              <li>With Your consent</li>
            </ul>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Retention of Your Personal Data</h2>
            <p>
              The Company will retain Your Personal Data only for as long as necessary for the purposes set
              out in this Privacy Policy and to comply with legal obligations.
            </p>
            <p>
              Usage Data is generally retained for a shorter period unless required for security or legal
              purposes.
            </p>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Transfer of Your Personal Data</h2>
            <p>
              Your information may be processed at the Company's operating offices and other locations
              where parties involved in processing are located.
            </p>
            <p>By using the Service and submitting information, You agree to such transfers.</p>
            <p>We take all reasonable steps necessary to ensure Your data is treated securely.</p>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Delete Your Personal Data</h2>
            <p>
              You have the right to delete or request assistance in deleting the Personal Data We have
              collected about You.
            </p>
            <p>You may contact Us to:</p>
            <ul className="list-disc pl-6 space-y-2 my-4">
              <li>Access Your data</li>
              <li>Correct Your data</li>
              <li>Delete Your data</li>
            </ul>
            <p>However, certain information may be retained where legally required.</p>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Disclosure of Your Personal Data</h2>
            
            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-3">Business Transactions</h3>
            <p>
              If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be
              transferred.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-3">Law Enforcement</h3>
            <p>
              The Company may disclose Your Personal Data if required to do so by law or in response to
              valid requests by public authorities.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-3">Other Legal Requirements</h3>
            <p>The Company may disclose Your Personal Data to:</p>
            <ul className="list-disc pl-6 space-y-2 my-4">
              <li>Comply with legal obligations</li>
              <li>Protect and defend Company rights or property</li>
              <li>Prevent wrongdoing</li>
              <li>Protect user safety</li>
              <li>Protect against legal liability</li>
            </ul>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us. While We strive to use commercially
              acceptable means to protect Your Personal Data, no method of transmission over the Internet is
              completely secure.
            </p>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Children's Privacy</h2>
            <p>Our Service does not address anyone under the age of 13.</p>
            <p>
              We do not knowingly collect personally identifiable information from children under 13. If We
              become aware that such information has been collected, We will take steps to remove it.
            </p>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Links to Other Websites</h2>
            <p>Our Service may contain links to third-party websites that are not operated by Us.</p>
            <p>We strongly advise You to review the Privacy Policy of every website You visit.</p>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Changes to This Privacy Policy</h2>
            <p>We may update Our Privacy Policy from time to time.</p>
            <p>Any changes will be posted on this page with an updated revision date.</p>
            <p>You are advised to review this Privacy Policy periodically.</p>

            <h2 className="text-2xl font-bold text-[#0e5872] mt-10 mb-4">Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <div className="bg-gray-50 p-6 rounded-lg mt-4 border border-gray-100">
              <p className="font-bold text-[#0e5872] mb-2">Dr. Aravind Manoharan</p>
              <ul className="space-y-2">
                <li>📧 Email: draravindmano@gmail.com</li>
                <li>📞 Phone: +91 72002 85569</li>
                <li>📍 Address: No.20, Old 12, Govinda St, Ayyavoo Colony, Chennai – 600029</li>
              </ul>
            </div>

          </div>
        </div>
      </section>
    </main>
  );
};
